version: '3.8'
services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    ports:
      - '8000:8000'
      - '9000:9000'
    expose:
      - '9000'

  mqtt-broker:
    container_name: vernemq
    image: vernemq/vernemq
    restart: always
    volumes:
      - /data/vernemq/data:/vernemq/data
      - /var/log/vernemq:/vernemq/log
    ports:
      - '1883:1883'
    expose:
      - '1883'
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
    environment:
      - TZ=Europe/London
    restart: always
    network_mode: host
