version: '3.8'
services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    network_mode: bridge
    ports:
      - "80:80"
      - "8080:8080"
    expose:
      - '80'
      - '8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    ports:
      - '8000:8000'
      - '9000:9000'
    labels:
      - traefik.http.routers.portainer.rule=Path("/portainer")

  mqtt-broker:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    network_mode: bridge
    volumes:
      - /data/mosquitto:/mosquitto/data
      - /var/log/mosquitto:/mosquitto/log
      - ./mosquitto:/mosquitto/config
    ports:
      - '1883:1883'
      - '9001:9001'
    expose:
      - '1883'
      - '9001'

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant:/config
    environment:
      - TZ=Europe/London
    restart: always
    network_mode: host

