title: Château Rowe
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.eleanor
      - entity: person.imogen
      - entity: person.chris
      - entity: sensor.cinema_room_switch_battery_level
      - entity: sensor.hue_dimmer_switch_1_battery_level
      - entity: sun.sun
    cards:
      - type: entities
        entities:
          - light.cinema_room
          - light.cinema_room_light
          - light.desk_lamp
          - light.front_door
          - light.group_for_wakeup
          - light.hallway
          - light.kitchen_patio
          - light.lounge_patio
          - light.master_bedroom
          - light.nightlight
          - light.office
          - light.office_light
          - light.outside
          - light.patio
          - light.porch_light
          - light.spotlight
        title: Light
      - type: weather-forecast
        entity: weather.home
        show_forecast: false

  - title: Cinema Room
    path: cinema_room
    cards:
      - type: entities
        entities:
          - light.cinema_room_light
          - light.spotlight
      - type: media-control
        entity: media_player.samsungtv_c19ca11f_cb80_4a51_95aa_65f8bd1a055c

  - title: Exterior
    path: exterior
    cards:
      - type: picture-entity
        entity: camera.driveway_front_garden
      - type: picture-entity
        entity: camera.driveway_garage
      - type: picture-entity
        entity: camera.side_garden
      - type: picture-entity
        entity: camera.rear_garden
      - type: picture-entity
        entity: camera.rear_patio

